# Custom Language File for Launcher Customizer

[ejs.app]
title = "해돋이-임시런처"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/sunrise-hwt1014"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "https://ch.sooplive.co.kr/hwt1014"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/sunrise-hwt1014"
supportLink = "https://github.com/CustomLauncherLab/sunrise-hwt1014/issues"

[ejs.welcome]
welcomeHeader = "해돋이-임시런처"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."